name: Notifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  messageTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: "Hello, this is a test message from GitHub Actions."

