name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  messageTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: actions/checkout@v2  
        env:
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.CHAT_ID }}
